"""initial

Revision ID: 41c555d9a667
Revises: 
Create Date: 2017-07-23 15:35:34.922416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41c555d9a667'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracked_kill',
    sa.Column('kill_tracking_label', sa.String(length=255), nullable=False),
    sa.Column('kill_id', sa.Integer(), nullable=False),
    sa.Column('kill_timestamp', sa.DateTime(), nullable=False),
    sa.Column('ship_id', sa.Integer(), nullable=False),
    sa.Column('ship_name', sa.String(length=50), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('character_name', sa.String(length=255), nullable=False),
    sa.Column('corporation_id', sa.Integer(), nullable=False),
    sa.Column('corporation_name', sa.String(length=255), nullable=False),
    sa.Column('alliance_id', sa.Integer(), nullable=True),
    sa.Column('alliance_name', sa.String(length=255), nullable=True),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('system_name', sa.String(length=50), nullable=False),
    sa.Column('more_info_href', sa.String(length=255), nullable=False),
    sa.Column('full_response', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('kill_tracking_label', 'kill_id')
    )
    op.create_index('idx_tracked_kill_by_label_timestamp', 'tracked_kill', ['kill_tracking_label', sa.text('kill_timestamp DESC'), 'kill_id', 'more_info_href'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tracked_kill_by_label_timestamp', table_name='tracked_kill')
    op.drop_table('tracked_kill')
    # ### end Alembic commands ###
