"""add item system lookup tables

Revision ID: 274d3d938628
Revises: 9b1f868a7343
Create Date: 2017-07-26 21:28:41.772392

  Copyright (c) 2016-2017 Tony Lechner and contributors

  testrattingcapitals.com is free software: you can redistribute it and/or
  modify it under the terms of the GNU Affero General Public License as
  published by the Free Software Foundation, either version 3 of the
  License, or (at your option) any later version.

  testrattingcapitals.com is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU Affero General Public License for more details.

  You should have received a copy of the GNU Affero General Public License
  along with testrattingcapitals.com.  If not, see
  <http://www.gnu.org/licenses/>.
"""
from alembic import op
import csv
import sqlalchemy as sa

from testrattingcapitals.db import Context
from testrattingcapitals.schema import EveItem, EveSolarSystem


# revision identifiers, used by Alembic.
revision = '274d3d938628'
down_revision = '9b1f868a7343'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eve_item',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eve_system',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('constellation_id', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    _upgrade_import_eve_items()
    _upgrade_import_eve_solar_systems()


def _upgrade_import_eve_items():
    with open('./migrations/data/inventory_type_dump_20170727_0211.csv', 'r', newline='') as file_handler:
        with Context() as db_context:
            reader = csv.reader(file_handler)
            through_header = False
            for row in reader:
                if not through_header: # skip the header
                    through_header = True
                    continue
                db_context.session.add(EveItem(id=int(row[0]), name=row[2]))
            db_context.session.commit()

def _upgrade_import_eve_solar_systems():
    with open('./migrations/data/solar_system_dump_20170727_0211.csv', 'r', newline='') as file_handler:
        with Context() as db_context:
            reader = csv.reader(file_handler)
            through_header = False
            for row in reader:
                if not through_header: # skip the header
                    through_header = True
                    continue
                db_context.session.add(EveSolarSystem(
                    id=int(row[2]),
                    constellation_id=int(row[1]),
                    region_id=int(row[0]),
                    name=row[3])
                )
            db_context.session.commit()




def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eve_system')
    op.drop_table('eve_item')
    # ### end Alembic commands ###
